"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-10

Mirrors docs/TECHNICAL-ARCHITECTURE.md § Database Schema. Hand-written
(not autogenerated) so the table-by-table layout is reviewable. GIN
indexes on ``text[]`` columns and the partial unique index on
``magic_link_tokens`` are Postgres-specific — the test fixture uses
``SQLModel.metadata.create_all`` on SQLite, not these migrations.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.Text(), nullable=False, unique=True),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "taste_profiles",
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column(
            "genres",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "tones",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "form_lengths",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_taste_profiles_genres_gin",
        "taste_profiles",
        ["genres"],
        postgresql_using="gin",
    )
    op.create_index(
        "ix_taste_profiles_tones_gin",
        "taste_profiles",
        ["tones"],
        postgresql_using="gin",
    )
    op.create_index(
        "ix_taste_profiles_form_lengths_gin",
        "taste_profiles",
        ["form_lengths"],
        postgresql_using="gin",
    )

    op.create_table(
        "posts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "author_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("genres", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("tones", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("form_length", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_posts_author_id", "posts", ["author_id"])
    op.create_index(
        "ix_posts_status_published_at",
        "posts",
        ["status", sa.text("published_at DESC")],
    )
    op.create_index(
        "ix_posts_genres_gin",
        "posts",
        ["genres"],
        postgresql_using="gin",
    )
    op.create_index(
        "ix_posts_tones_gin",
        "posts",
        ["tones"],
        postgresql_using="gin",
    )

    op.create_table(
        "comments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "post_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("posts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "author_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "parent_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("comments.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_comments_post_id", "comments", ["post_id"])
    op.create_index("ix_comments_author_id", "comments", ["author_id"])
    op.create_index("ix_comments_parent_id", "comments", ["parent_id"])
    op.create_index(
        "ix_comments_post_status_created",
        "comments",
        ["post_id", "status", "created_at"],
    )

    op.create_table(
        "moderation_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("subject_type", sa.Text(), nullable=False),
        sa.Column("subject_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("raw_response", postgresql.JSONB(), nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("categories", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("max_score", sa.Numeric(), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_moderation_results_subject",
        "moderation_results",
        ["subject_type", "subject_id"],
    )

    op.create_table(
        "magic_link_tokens",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("token_hash", postgresql.BYTEA(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_magic_link_tokens_email", "magic_link_tokens", ["email"])
    op.create_index(
        "ix_magic_link_tokens_token_hash_unconsumed",
        "magic_link_tokens",
        ["token_hash"],
        postgresql_where=sa.text("consumed_at IS NULL"),
    )


def downgrade() -> None:
    op.drop_table("magic_link_tokens")
    op.drop_table("moderation_results")
    op.drop_table("comments")
    op.drop_table("posts")
    op.drop_table("taste_profiles")
    op.drop_table("users")
